# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_otherwindow(object):
    def setupUi(self, otherwindow):
        otherwindow.setObjectName("otherwindow")
        otherwindow.resize(959, 729)
        self.centralwidget = QtWidgets.QWidget(otherwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.original_sign = PlotWidget(self.centralwidget)
        self.original_sign.setObjectName("original_sign")
        self.verticalLayout_7.addWidget(self.original_sign)
        self.original_frequ = PlotWidget(self.centralwidget)
        self.original_frequ.setObjectName("original_frequ")
        self.verticalLayout_7.addWidget(self.original_frequ)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_6.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.output1_sig = PlotWidget(self.centralwidget)
        self.output1_sig.setObjectName("output1_sig")
        self.verticalLayout_6.addWidget(self.output1_sig)
        self.output11 = PlotWidget(self.centralwidget)
        self.output11.setObjectName("output11")
        self.verticalLayout_6.addWidget(self.output11)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_9.addWidget(self.lineEdit_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.output2_sig = PlotWidget(self.centralwidget)
        self.output2_sig.setObjectName("output2_sig")
        self.verticalLayout_9.addWidget(self.output2_sig)
        self.output22 = PlotWidget(self.centralwidget)
        self.output22.setObjectName("output22")
        self.verticalLayout_9.addWidget(self.output22)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("background-color: rgb(242, 242, 242);")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.diff_sig = PlotWidget(self.centralwidget)
        self.diff_sig.setObjectName("diff_sig")
        self.verticalLayout.addWidget(self.diff_sig)
        self.diff_freq = PlotWidget(self.centralwidget)
        self.diff_freq.setObjectName("diff_freq")
        self.verticalLayout.addWidget(self.diff_freq)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        otherwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(otherwindow)
        self.statusbar.setObjectName("statusbar")
        otherwindow.setStatusBar(self.statusbar)

        self.retranslateUi(otherwindow)
        QtCore.QMetaObject.connectSlotsByName(otherwindow)

    def retranslateUi(self, otherwindow):
        _translate = QtCore.QCoreApplication.translate
        otherwindow.setWindowTitle(_translate("otherwindow", "MainWindow"))
        self.lineEdit.setText(_translate("otherwindow", "Originl Signal "))
        self.lineEdit_2.setText(_translate("otherwindow", "Output 1"))
        self.lineEdit_3.setText(_translate("otherwindow", "Output 2"))
        self.lineEdit_4.setText(_translate("otherwindow", "Signal Difference"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    otherwindow = QtWidgets.QMainWindow()
    ui = Ui_otherwindow()
    ui.setupUi(otherwindow)
    otherwindow.show()
    sys.exit(app.exec_())

