# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.Svalue1 = QtWidgets.QLineEdit(self.frame)
        self.Svalue1.setEnabled(True)
        self.Svalue1.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.Svalue1.setFrame(False)
        self.Svalue1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Svalue1.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue1.setReadOnly(True)
        self.Svalue1.setObjectName("Svalue1")
        self.horizontalLayout_9.addWidget(self.Svalue1)
        self.Svalue2 = QtWidgets.QLineEdit(self.frame)
        self.Svalue2.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.Svalue2.setFrame(False)
        self.Svalue2.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue2.setReadOnly(True)
        self.Svalue2.setObjectName("Svalue2")
        self.horizontalLayout_9.addWidget(self.Svalue2)
        self.Svalue3 = QtWidgets.QLineEdit(self.frame)
        self.Svalue3.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.Svalue3.setFrame(False)
        self.Svalue3.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue3.setReadOnly(True)
        self.Svalue3.setObjectName("Svalue3")
        self.horizontalLayout_9.addWidget(self.Svalue3)
        self.Svalue4 = QtWidgets.QLineEdit(self.frame)
        self.Svalue4.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.Svalue4.setFrame(False)
        self.Svalue4.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue4.setReadOnly(True)
        self.Svalue4.setObjectName("Svalue4")
        self.horizontalLayout_9.addWidget(self.Svalue4)
        self.Svalue5 = QtWidgets.QLineEdit(self.frame)
        self.Svalue5.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"")
        self.Svalue5.setFrame(False)
        self.Svalue5.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue5.setReadOnly(True)
        self.Svalue5.setObjectName("Svalue5")
        self.horizontalLayout_9.addWidget(self.Svalue5)
        self.Svalue6 = QtWidgets.QLineEdit(self.frame)
        self.Svalue6.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"")
        self.Svalue6.setFrame(False)
        self.Svalue6.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue6.setReadOnly(True)
        self.Svalue6.setObjectName("Svalue6")
        self.horizontalLayout_9.addWidget(self.Svalue6)
        self.Svalue7 = QtWidgets.QLineEdit(self.frame)
        self.Svalue7.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.Svalue7.setFrame(False)
        self.Svalue7.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue7.setReadOnly(True)
        self.Svalue7.setObjectName("Svalue7")
        self.horizontalLayout_9.addWidget(self.Svalue7)
        self.Svalue8 = QtWidgets.QLineEdit(self.frame)
        self.Svalue8.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.Svalue8.setFrame(False)
        self.Svalue8.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue8.setReadOnly(True)
        self.Svalue8.setObjectName("Svalue8")
        self.horizontalLayout_9.addWidget(self.Svalue8)
        self.Svalue9 = QtWidgets.QLineEdit(self.frame)
        self.Svalue9.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.Svalue9.setFrame(False)
        self.Svalue9.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue9.setReadOnly(True)
        self.Svalue9.setObjectName("Svalue9")
        self.horizontalLayout_9.addWidget(self.Svalue9)
        self.Svalue10 = QtWidgets.QLineEdit(self.frame)
        self.Svalue10.setAutoFillBackground(False)
        self.Svalue10.setStyleSheet("background-color: rgb(235, 235, 235);    \n"
"            \n"
"\n"
"")
        self.Svalue10.setMaxLength(32807)
        self.Svalue10.setFrame(False)
        self.Svalue10.setAlignment(QtCore.Qt.AlignCenter)
        self.Svalue10.setReadOnly(True)
        self.Svalue10.setObjectName("Svalue10")
        self.horizontalLayout_9.addWidget(self.Svalue10)
        spacerItem1 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Band1 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band1.sizePolicy().hasHeightForWidth())
        self.Band1.setSizePolicy(sizePolicy)
        self.Band1.setMinimum(-15)
        self.Band1.setMaximum(15)
        self.Band1.setOrientation(QtCore.Qt.Vertical)
        self.Band1.setObjectName("Band1")
        self.horizontalLayout.addWidget(self.Band1)
        self.Band2 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band2.sizePolicy().hasHeightForWidth())
        self.Band2.setSizePolicy(sizePolicy)
        self.Band2.setMinimum(-15)
        self.Band2.setMaximum(15)
        self.Band2.setOrientation(QtCore.Qt.Vertical)
        self.Band2.setObjectName("Band2")
        self.horizontalLayout.addWidget(self.Band2)
        self.Band3 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band3.sizePolicy().hasHeightForWidth())
        self.Band3.setSizePolicy(sizePolicy)
        self.Band3.setMinimum(-15)
        self.Band3.setMaximum(15)
        self.Band3.setOrientation(QtCore.Qt.Vertical)
        self.Band3.setObjectName("Band3")
        self.horizontalLayout.addWidget(self.Band3)
        self.Band4 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band4.sizePolicy().hasHeightForWidth())
        self.Band4.setSizePolicy(sizePolicy)
        self.Band4.setMinimum(-15)
        self.Band4.setMaximum(15)
        self.Band4.setOrientation(QtCore.Qt.Vertical)
        self.Band4.setObjectName("Band4")
        self.horizontalLayout.addWidget(self.Band4)
        self.Band5 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band5.sizePolicy().hasHeightForWidth())
        self.Band5.setSizePolicy(sizePolicy)
        self.Band5.setMinimum(-15)
        self.Band5.setMaximum(15)
        self.Band5.setOrientation(QtCore.Qt.Vertical)
        self.Band5.setObjectName("Band5")
        self.horizontalLayout.addWidget(self.Band5)
        self.Band6 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band6.sizePolicy().hasHeightForWidth())
        self.Band6.setSizePolicy(sizePolicy)
        self.Band6.setMinimum(-15)
        self.Band6.setMaximum(15)
        self.Band6.setOrientation(QtCore.Qt.Vertical)
        self.Band6.setObjectName("Band6")
        self.horizontalLayout.addWidget(self.Band6)
        self.Band7 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band7.sizePolicy().hasHeightForWidth())
        self.Band7.setSizePolicy(sizePolicy)
        self.Band7.setMinimum(-15)
        self.Band7.setMaximum(15)
        self.Band7.setOrientation(QtCore.Qt.Vertical)
        self.Band7.setObjectName("Band7")
        self.horizontalLayout.addWidget(self.Band7)
        self.Band8 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band8.sizePolicy().hasHeightForWidth())
        self.Band8.setSizePolicy(sizePolicy)
        self.Band8.setStyleSheet("gridline-color: rgb(99, 255, 75);")
        self.Band8.setMinimum(-15)
        self.Band8.setMaximum(15)
        self.Band8.setOrientation(QtCore.Qt.Vertical)
        self.Band8.setObjectName("Band8")
        self.horizontalLayout.addWidget(self.Band8)
        self.Band9 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band9.sizePolicy().hasHeightForWidth())
        self.Band9.setSizePolicy(sizePolicy)
        self.Band9.setMinimum(-15)
        self.Band9.setMaximum(15)
        self.Band9.setOrientation(QtCore.Qt.Vertical)
        self.Band9.setObjectName("Band9")
        self.horizontalLayout.addWidget(self.Band9)
        self.Band10 = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Band10.sizePolicy().hasHeightForWidth())
        self.Band10.setSizePolicy(sizePolicy)
        self.Band10.setMinimum(-15)
        self.Band10.setMaximum(15)
        self.Band10.setOrientation(QtCore.Qt.Vertical)
        self.Band10.setObjectName("Band10")
        self.horizontalLayout.addWidget(self.Band10)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_33.setEnabled(True)
        self.lineEdit_33.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_3.addWidget(self.lineEdit_33)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_34.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_3.addWidget(self.lineEdit_34)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_35.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_3.addWidget(self.lineEdit_35)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_36.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.horizontalLayout_3.addWidget(self.lineEdit_36)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_37.sizePolicy().hasHeightForWidth())
        self.lineEdit_37.setSizePolicy(sizePolicy)
        self.lineEdit_37.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.horizontalLayout_3.addWidget(self.lineEdit_37)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_38.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"")
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_3.addWidget(self.lineEdit_38)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_39.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"")
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.horizontalLayout_3.addWidget(self.lineEdit_39)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_40.sizePolicy().hasHeightForWidth())
        self.lineEdit_40.setSizePolicy(sizePolicy)
        self.lineEdit_40.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"")
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.horizontalLayout_3.addWidget(self.lineEdit_40)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_41.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.horizontalLayout_3.addWidget(self.lineEdit_41)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_42.setFont(font)
        self.lineEdit_42.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.lineEdit_42.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.horizontalLayout_3.addWidget(self.lineEdit_42)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Playbutton = QtWidgets.QToolButton(self.horizontalFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/play-1962689-1660354.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Playbutton.setIcon(icon)
        self.Playbutton.setObjectName("Playbutton")
        self.horizontalLayout_2.addWidget(self.Playbutton)
        self.Stopbutton = QtWidgets.QToolButton(self.horizontalFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/unnamed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stopbutton.setIcon(icon1)
        self.Stopbutton.setObjectName("Stopbutton")
        self.horizontalLayout_2.addWidget(self.Stopbutton)
        self.Play1 = QtWidgets.QRadioButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Play1.setFont(font)
        self.Play1.setStyleSheet("color: rgb(75, 255, 90);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"")
        self.Play1.setObjectName("Play1")
        self.horizontalLayout_2.addWidget(self.Play1)
        self.Play2 = QtWidgets.QRadioButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Play2.setFont(font)
        self.Play2.setStyleSheet("background-color:rgb(170, 0, 0);    \n"
"color: rgb(255, 255, 255);")
        self.Play2.setObjectName("Play2")
        self.horizontalLayout_2.addWidget(self.Play2)
        self.verticalLayout_5.addWidget(self.horizontalFrame)
        self.horizontalLayout_10.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(self.widget)
        self.frame1.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_7.addWidget(self.lineEdit_3)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_25.sizePolicy().hasHeightForWidth())
        self.lineEdit_25.setSizePolicy(sizePolicy)
        self.lineEdit_25.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout_7.addWidget(self.lineEdit_25)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_7.addWidget(self.lineEdit_4)
        self.Output1 = QtWidgets.QRadioButton(self.frame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Output1.setFont(font)
        self.Output1.setStyleSheet("color: rgb(75, 255, 90);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"\n"
"")
        self.Output1.setObjectName("Output1")
        self.verticalLayout_7.addWidget(self.Output1)
        self.Output2 = QtWidgets.QRadioButton(self.frame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Output2.setFont(font)
        self.Output2.setStyleSheet("background-color:rgb(170, 0, 0);    \n"
"color: rgb(255, 255, 255);")
        self.Output2.setObjectName("Output2")
        self.verticalLayout_7.addWidget(self.Output2)
        self.horizontalLayout_10.addWidget(self.frame1)
        self.verticalFrame = QtWidgets.QFrame(self.widget)
        self.verticalFrame.setMinimumSize(QtCore.QSize(0, 258))
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame.setLineWidth(2)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pbzeroall = QtWidgets.QPushButton(self.verticalFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/Abdulla Elsayed/.designer/SBME/8c897236.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbzeroall.setIcon(icon2)
        self.pbzeroall.setIconSize(QtCore.QSize(22, 21))
        self.pbzeroall.setObjectName("pbzeroall")
        self.verticalLayout_2.addWidget(self.pbzeroall)
        self.savept = QtWidgets.QPushButton(self.verticalFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savept.setIcon(icon3)
        self.savept.setObjectName("savept")
        self.verticalLayout_2.addWidget(self.savept)
        self.load = QtWidgets.QPushButton(self.verticalFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/16-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load.setIcon(icon4)
        self.load.setObjectName("load")
        self.verticalLayout_2.addWidget(self.load)
        self.comboBox = QtWidgets.QComboBox(self.verticalFrame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout_10.addWidget(self.verticalFrame)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.modified_frequ = PlotWidget(self.widget)
        self.modified_frequ.setStyleSheet("color: rgb(0, 0, 127);")
        self.modified_frequ.setObjectName("modified_frequ")
        self.verticalLayout_3.addWidget(self.modified_frequ)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.showsignal = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/medical-health-pulse-ekg-ecg-cardiograph-hearth-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showsignal.setIcon(icon5)
        self.showsignal.setObjectName("showsignal")
        self.gridLayout_4.addWidget(self.showsignal, 4, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame2.setLineWidth(2)
        self.frame2.setObjectName("frame2")
        self.gridLayout_4.addWidget(self.frame2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEquilizer = QtWidgets.QMenu(self.menubar)
        self.menuEquilizer.setObjectName("menuEquilizer")
        self.menuPlayback = QtWidgets.QMenu(self.menubar)
        self.menuPlayback.setObjectName("menuPlayback")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd_Files = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Files.setIcon(icon6)
        self.actionAdd_Files.setShortcutVisibleInContextMenu(False)
        self.actionAdd_Files.setObjectName("actionAdd_Files")
        self.actionAdd_Folders = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/file.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Folders.setIcon(icon7)
        self.actionAdd_Folders.setObjectName("actionAdd_Folders")
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/Omar/Downloads/delete-1432400-1211078.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon8)
        self.actionClear.setObjectName("actionClear")
        self.actionzeroall = QtWidgets.QAction(MainWindow)
        self.actionzeroall.setObjectName("actionzeroall")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.addfilesmb = QtWidgets.QAction(MainWindow)
        self.addfilesmb.setObjectName("addfilesmb")
        self.actionAdd_Folders_2 = QtWidgets.QAction(MainWindow)
        self.actionAdd_Folders_2.setObjectName("actionAdd_Folders_2")
        self.actionRemove_2 = QtWidgets.QAction(MainWindow)
        self.actionRemove_2.setObjectName("actionRemove_2")
        self.actionClear_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_2.setObjectName("actionClear_2")
        self.actionConvert = QtWidgets.QAction(MainWindow)
        self.actionConvert.setObjectName("actionConvert")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionRewind = QtWidgets.QAction(MainWindow)
        self.actionRewind.setObjectName("actionRewind")
        self.actionForward = QtWidgets.QAction(MainWindow)
        self.actionForward.setObjectName("actionForward")
        self.save1 = QtWidgets.QAction(MainWindow)
        self.save1.setObjectName("save1")
        self.save2 = QtWidgets.QAction(MainWindow)
        self.save2.setObjectName("save2")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.addfilesmb)
        self.menuFile.addAction(self.actionClear_2)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEquilizer.addAction(self.actionzeroall)
        self.menuEquilizer.addAction(self.actionSave)
        self.menuEquilizer.addAction(self.actionLoad)
        self.menuPlayback.addAction(self.actionPlay)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEquilizer.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionAdd_Files)
        self.toolBar.addAction(self.actionClear)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EQ"))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Svalue1.setText(_translate("MainWindow", "0"))
        self.Svalue2.setText(_translate("MainWindow", "0"))
        self.Svalue3.setText(_translate("MainWindow", "0"))
        self.Svalue4.setText(_translate("MainWindow", "0"))
        self.Svalue5.setText(_translate("MainWindow", "0"))
        self.Svalue6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Svalue6.setText(_translate("MainWindow", "0"))
        self.Svalue7.setText(_translate("MainWindow", "0"))
        self.Svalue8.setText(_translate("MainWindow", "0"))
        self.Svalue9.setText(_translate("MainWindow", "0"))
        self.Svalue10.setText(_translate("MainWindow", "0"))
        self.lineEdit_33.setText(_translate("MainWindow", "31"))
        self.lineEdit_34.setText(_translate("MainWindow", "62"))
        self.lineEdit_35.setText(_translate("MainWindow", "125"))
        self.lineEdit_36.setText(_translate("MainWindow", "250"))
        self.lineEdit_37.setText(_translate("MainWindow", "500"))
        self.lineEdit_38.setText(_translate("MainWindow", "1K"))
        self.lineEdit_39.setText(_translate("MainWindow", "2K"))
        self.lineEdit_40.setText(_translate("MainWindow", "4K"))
        self.lineEdit_41.setText(_translate("MainWindow", "8K"))
        self.lineEdit_42.setText(_translate("MainWindow", "16K"))
        self.Playbutton.setText(_translate("MainWindow", "..."))
        self.Stopbutton.setText(_translate("MainWindow", "..."))
        self.Play1.setText(_translate("MainWindow", "Play 1"))
        self.Play2.setText(_translate("MainWindow", "Play 2"))
        self.lineEdit_3.setText(_translate("MainWindow", "+15 DB"))
        self.lineEdit_25.setText(_translate("MainWindow", "0 DB"))
        self.lineEdit_4.setText(_translate("MainWindow", "-15 DB"))
        self.Output1.setText(_translate("MainWindow", "Output1"))
        self.Output2.setText(_translate("MainWindow", "Output2"))
        self.pbzeroall.setText(_translate("MainWindow", "Zero All"))
        self.savept.setText(_translate("MainWindow", "Save"))
        self.load.setText(_translate("MainWindow", "Load"))
        self.comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Rectangular"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hamming"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Hanning"))
        self.showsignal.setText(_translate("MainWindow", "Show Difference"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEquilizer.setTitle(_translate("MainWindow", "Equilizer"))
        self.menuPlayback.setTitle(_translate("MainWindow", "Playback"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAdd_Files.setText(_translate("MainWindow", "Add Files"))
        self.actionAdd_Folders.setText(_translate("MainWindow", "Add Folders "))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionzeroall.setText(_translate("MainWindow", "Zero All"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.addfilesmb.setText(_translate("MainWindow", "Add Files"))
        self.actionAdd_Folders_2.setText(_translate("MainWindow", "Add Folders"))
        self.actionRemove_2.setText(_translate("MainWindow", "Remove"))
        self.actionClear_2.setText(_translate("MainWindow", "Clear"))
        self.actionConvert.setText(_translate("MainWindow", "Convert"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionRewind.setText(_translate("MainWindow", "Rewind"))
        self.actionForward.setText(_translate("MainWindow", "Forward"))
        self.save1.setText(_translate("MainWindow", "file1"))
        self.save2.setText(_translate("MainWindow", "file2"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

